server:
  host: localhost
  port: 3000
  mode: debug

jwt:
  secretKey: "Matkhau@1234Nam"
  expIn: 3600

postgres:
  host: "localhost"
  port: 5432
  user: "keycloak"
  password: "password"
  name: "keycloak"
  schema: "public"
  dbname: "keycloak"
  debug: true
  sslmode: "disable"

replica_postgres:
  host: "localhost"
  port: 5432
  user: "keycloak"
  password: "password"
  name: "keycloak"
  schema: "public"
  dbname: "keycloak"
  debug: true
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

account_client:
  base_url: https://api.example.com
  timeout: 10s
  retry_count: 3
  retry_wait: 2s
  debug: true
  headers:
    Authorization: Bearer your-token
    Content-Type: application/json

consumer_client:
  base_url: https://api.example.com
  timeout: 10s
  retry_count: 3
  retry_wait: 2s
  headers:
    Authorization: Bearer your-token
    Content-Type: application/json

cron:
  link-account: "*/30 * * * * *"
  notify: "*/5 * * * * *"
