server:
  host: localhost
  port: 8081
  mode: debug
  root-path: "/api"
  engine: "gin"

jwt:
  secretKey: "Matkhau@1234Nam"
  expIn: 3600

postgres:
  host: "localhost"
  port: 5432
  user: "keycloak"
  password: "password"
  name: "keycloak"
  schema: "public"
  dbname: "keycloak"
  debug: true
  sslmode: "disable"
  driver: "postgres"

replica_postgres:
  host: "localhost"
  port: 5432
  user: "keycloak"
  password: "password"
  name: "keycloak"
  schema: "public"
  dbname: "keycloak"
  debug: true
  sslmode: "disable"
  driver: "postgres"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

account_client:
  url: http://localhost:8081/api/v1
  timeout: 10s
  retry_count: 3
  retry_wait: 2s
  debug: true
  headers:
    Authorization: Bearer your-token
    Content-Type: application/json

consumer_client:
  url: http://localhost:8081/api/v1
  timeout: 10s
  retry_count: 3
  retry_wait: 2s
  headers:
    Authorization: Bearer your-token
    Content-Type: application/json

cron:
  link-account: "*/6 * * * * *"
  notify: "*/5 * * * * *"