// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kimxuanhong/go-example/internal/infrastructure/repository"
	"github.com/kimxuanhong/go-example/internal/interface/handler"
	"github.com/kimxuanhong/go-example/internal/usecase"
	"github.com/kimxuanhong/go-http/server"
	"github.com/kimxuanhong/go-postgres/postgres"
	"github.com/kimxuanhong/go-redis/redis"
	"github.com/kimxuanhong/go-utils/config"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	config, err := LoadConfig()
	if err != nil {
		return nil, err
	}
	server, err := InitHttpServer(config)
	if err != nil {
		return nil, err
	}
	postgres, err := InitPostgres(config)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepo(postgres)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandler := handler.NewUserHandler(userUsecase)
	app := &App{
		Cfg:         config,
		Server:      server,
		UserHandler: userHandler,
	}
	return app, nil
}

// wire.go:

type Config struct {
	Server   *server.Config   `yaml:"server"`
	Redis    *redis.Config    `yaml:"redis,omitempty"`
	Postgres *postgres.Config `yaml:"postgres,omitempty"`
}

type App struct {
	Cfg         *Config
	Server      server.Server
	UserHandler *handler.UserHandler
}

// Tạo một provider cho config
func LoadConfig() (*Config, error) {
	cfg, err := config.LoadConfig[Config]()
	if err != nil {
		return nil, err
	}
	return cfg, nil
}

// Server luôn được khởi tạo từ cấu hình
func InitHttpServer(cfg *Config) (server.Server, error) {
	return server.NewServer(cfg.Server), nil
}

// Postgres chỉ được khởi tạo nếu có config postgres
func InitPostgres(cfg *Config) (postgres.Postgres, error) {
	return postgres.NewPostgres(cfg.Postgres)
}

// Redis chỉ được khởi tạo nếu có config redis
func InitRedis(cfg *Config) (redis.Redis, error) {
	return redis.NewRedis(cfg.Redis)
}
